name: Publish package to GitHub Packages
on:
  push:
    branches: [master]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Publish package
        run: sbt test publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

